- hosts: localhost
  vars_files:
    - vars/alteon_params.yml
  tasks:
  - name: install genisoimage
    package:
      name: genisoimage
      state: present
  
  - name: Create Alteon config file 
    copy:
      dest: "/tmp/iso_cfg.txt"
      content: |
        /c/sys/mmgmt
                dhcp disable
                addr6 3001:0:0:0:0:0:abcd:1234
                prefix6 64
                gw6 3001:0:0:0:0:0:abcd:2222

  - name: Create ISO file
    command: genisoimage -o /tmp/alteon_ipv6_ansible.iso /tmp/iso_cfg.txt

  - name: Copy file to datastore
    vsphere_copy:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      src: /tmp/alteon_ipv6_ansible.iso
      datacenter: NY
      datastore: datastore1
      path: /Folder/alteon_ipv6_ansible.iso
      validate_certs: no
    delegate_to: localhost
  
  - name: deploy from ovf
    vmware_deploy_ovf:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      ovf: /tmp/AlteonOS-32-4-0-5_rls_2.ova
      name: "{{ vm_name }}"
      validate_certs: no
      datacenter: NY
      datastore: datastore1
      power_on: no
      networks: {"Management": "VM Network", "Clients": "VM Network", "Servers": "VM Network"}
    delegate_to: localhost

  - name: Set cdrom to datastore
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ vm_name }}"
      folder: /
      datacenter: NY
      datastore: datastore1
      cdrom:
        type: iso
        iso_path: "[datastore1] /Folder/alteon_ipv6_ansible.iso"
    delegate_to: localhost

  - name: power on Alteon
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ vm_name }}"
      state: poweredon
      folder: /
      datacenter: NY
      datastore: datastore1
    delegate_to: localhost
